baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'React'
theme = 'hugo-theme-relearn'

[params]
  themeVariant = ['relearn-dark', 'relearn-light']

[outputs]
  home = ['html', 'rss', 'search', 'searchpage']