baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'React'
theme = 'hugo-theme-relearn'

[params]
  themeVariant = ['relearn-light', 'relearn-dark']
  highlightWrap = false

[outputs]
  home = ['html', 'rss', 'search', 'searchpage']